### ISSUE TITLE
Some common RSS feeds aren't recognized

### ISSUE THREAD

**Issue by augustf** [concerto/concerto-simple-rss#44]
When testing some random RSS feeds on the Web, I've noticed many that are not being recognized properly. The error comes in the form of Unable to preview. Unexpected feed format for http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml followed by the validation error "URL does not appear to be an RSS feed." Of course, all the of following feeds validate.

New York Times Front Page: http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml

BBC Top Stories: http://feeds.bbci.co.uk/news/rss.xml (and any feed on http://www.bbc.com/news/10628494)

Yahoo Investor news: http://apps.shareholder.com/rss/rss.aspx?channels=632&companyid=YHOO&sh_auth=605643764.0.0.42239.13052ac97a8d9805d5c39df9dd348d0c (and any feed on https://investor.yahoo.net/rss.cfm)

**Comment by augustf** [comment]
While I'm not able to reproduce this on my local working copy, it's definitely the case for the demo copy of Concerto I have online. The log error is:

I, [2015-08-21T21:57:54.455902 #14680]  INFO -- :   Parameters: {"data"=>{"url"=>"http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml", "output_format"=>"headlines", "max_items"=>"0", "reverse_order"=>"0", "xsl"=>"", "sanitize_tags"=>""}, "type"=>"SimpleRss"}
E, [2015-08-21T21:57:54.514129 #14680] ERROR -- : could not fetch UNKNOWN feed for  at http://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml

**Comment by kench** [comment]
Are you using an RSS gem?  Check the version you're using against the version running online.

**Comment by augustf** [comment]
The only RSS Gem involved is the concerto_simple_rss gem and its dependencies. It's 0.6 in both instances. I'll probably end up chalking this up to some instance-specific permission issue -- I can't think what other difference there might be between two deployments...and no one else has reported this.

**Comment by mfrederickson** [comment]
I am not able to reproduce it locally either.

**Comment by augustf** [comment]
Yeah-another re-install seems to have sorted it. I guess we'll stow this away for another report.
