### ISSUE TITLE
handle feeds requiring http basic authentication

### ISSUE THREAD

**Issue by mfrederickson** [concerto/concerto-simple-rss#45]
A user had a [request](https://groups.google.com/d/msg/concerto-digital-signage/zVoZUo7T9sY/LyzPvtHwCAAJ) to handle RSS feeds that required basic authentication.

Seems it is rather [easy to accommodate](http://blog.andreamostosi.name/2013/04/open-uri-and-basic-authentication/):

```
open("http://www.your-website.net", http_basic_authentication: ["user", "password"])
```

**Comment by augustf** [comment]
As we mentioned on the list post about this, we'll want to think carefully about how/where we store and handle these credentials.

**Comment by mfrederickson** [comment]
What about using attr_encryptor or whatever it's called?

**Comment by augustf** [comment]
Yeah-I think something like https://github.com/danpal/attr_encryptor will work just fine. We'll need to make some DB fields for that to happen.

**Comment by mfrederickson** [comment]
Actually they'd be stored in the config field I believe.  It is used as a catch all for derivative content types fields.

**Comment by kench** [comment]
Just an FYI, you want to make sure that the creds are removed when they're no longer used (feed deletion/modification).
