### ISSUE TITLE
XSLT Transform Functions

### ISSUE THREAD

**Issue by snoop168** [concerto/concerto-simple-rss#51]
[Transforming RSS with XSLT](https://github.com/concerto/concerto-simple-rss/wiki/Transforming-RSS-with-XSLT) contains some code that includes `   xmlns:fn="http://schemas.concerto-signage.org/functions" ` however the domain name no longer resolves...

**Comment by mfrederickson** [comment]
@snoop168 that is used for a distinct naming convention for a unique uri, not an actual DNS entry.

**Comment by mfrederickson** [comment]
That namespace makes the custom functions in the code available to the transformations.
https://github.com/concerto/concerto-simple-rss/blob/master/app/models/simple_rss.rb#L109

![image](https://cloud.githubusercontent.com/assets/473165/22032311/666c16d0-dc90-11e6-91f9-cbb1c0deb80d.png)
