### ISSUE TITLE
1.1 fails with bundler error on 2.3.5

### ISSUE THREAD

**Issue by augustf** [concerto/concerto-simple-rss#55]
When attempting to build 2.3.5, I got an issue with the RSS and video plugins I could not resolve. It didn't come up during testing or build but only for users upgrading their Concerto. This broke the Concerto VM severely. The message was "Downloading concerto_simple_rss-1.1 revealed dependencies not in the API or
the lockfile". The change was introduced with https://github.com/concerto/concerto-simple-rss/commit/a81e1a97f60f9b0d5052eca464a69a536480b4d9#diff-e46df9b753a8039982320fabb6a25b1aR21 and I was forced to revert the entire release, as the error could not be resolved on any of my installations.

**Comment by mfrederickson** [comment]
I don't suppose you have the screenshot for this one, like you do for the concerto remote video?  That one indicated a problem originating with the video_info, I believe.

**Comment by mfrederickson** [comment]
I did not see any errors with this repo when resolving the build issue (see https://github.com/concerto/concerto-remote-video/issues/41).
